// AUTO-GENERATED by scripts/build-knowledge.mjs — do not edit by hand.
// Source: the /knowledge folder. Regenerate with `npm run knowledge`.
export type FirmDoc = { id: string; title: string; text: string };

export const firmDocs: FirmDoc[] = [
  {
    "id": "doc:about-the-firm.md:0",
    "title": "About V K Munje & Company",
    "text": "V K Munje & Company is a firm of Cost Accountants based in Pune, established\nin 2019 and registered with the Institute of Cost Accountants of India (ICMAI)."
  },
  {
    "id": "doc:about-the-firm.md:1",
    "title": "About V K Munje & Company — Leadership",
    "text": "The firm is led by Founder & Principal CMA Vicky Munje (ACMA, LLB, M.Com),\nsupported by CA Deepak Mehta (ACA, Associate) and a professional team."
  },
  {
    "id": "doc:about-the-firm.md:2",
    "title": "About V K Munje & Company — Motto",
    "text": "\"Behind every successful business decision, there is always a CMA.\""
  },
  {
    "id": "doc:about-the-firm.md:3",
    "title": "About V K Munje & Company — Office and contact",
    "text": "- Office: Shop 2401, 24th Floor, Business Park, New Kalyani Nagar,\n  Wadgaon Sheri, Pune – 411014\n- Phone / WhatsApp: +91 99220 99970 (also +91 96573 75713)\n- Email: cma.vickymunje@gmail.com\n- Website: https://cmavkmunje.com"
  },
  {
    "id": "doc:about-the-firm.md:4",
    "title": "About V K Munje & Company — How to engage the firm",
    "text": "New clients can book a consultation from the website (Book Consultation page),\ncall or WhatsApp the office, or simply describe their requirement in this chat —\nthe team responds during office hours. Existing clients can upload documents\nthrough the Client Portal on the website."
  }
];
